# ================================= API ================================
FROM python:3.13-alpine AS cmdb-api

LABEL description="Python3.13,cmdb"

COPY cmdb-api /data/apps/cmdb

WORKDIR /data/apps/cmdb

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add --no-cache tzdata gcc musl-dev libffi-dev openldap-dev python3-dev jpeg-dev zlib-dev build-base

ENV TZ=Asia/Shanghai

RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple uv \
    && mkdir -p /root/.config/uv \
    && echo '[[index]]' > /root/.config/uv/uv.toml \
    && echo 'url = "https://mirrors.aliyun.com/pypi/simple/"' >> /root/.config/uv/uv.toml \
    && uv sync --no-dev \
    && uv cache clean

ADD docker/wait /wait
RUN chmod +x /wait

ENV PATH="/data/apps/cmdb/.venv/bin:$PATH"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]