# ================================= UI ================================
# docker.m.daocloud.io/library/node:16.20
# docker.m.daocloud.io/library/nginx:alpine
FROM node:16.20 AS builder

LABEL description="cmdb-ui"
ENV TZ=Asia/Shanghai
COPY cmdb-ui /data/apps/cmdb-ui

WORKDIR /data/apps/cmdb-ui

RUN sed -i "s#http://127.0.0.1:5000##g" .env && yarn install --ignore-engines --network-timeout 1000000  && yarn build

FROM nginx:alpine AS cmdb-ui
ENV TZ=Asia/Shanghai
RUN mkdir /etc/nginx/html && rm -f /etc/nginx/conf.d/default.conf

COPY --from=builder /data/apps/cmdb-ui/dist /etc/nginx/html/
